name: main

on: push

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"

      - run: npm install

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
      - run: npm run build
      - run: npm run lint
        env:
          CI: true
